# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hivemind_pb2 as hivemind__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivemind_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HiveMindStub:
    """HiveMind is the single shared gRPC service exposing every RPC this
    contract defines. A single service (rather than one per RPC-group) keeps
    the generated client/server surface simple -- engine/rpc/'s server
    implements HiveMindServer; engine/split/'s proposer_grpc.go (task-3.2.3)
    only calls HiveMindClient.ProposeSplit.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutSegment = channel.unary_unary(
                '/hivemind.v1.HiveMind/PutSegment',
                request_serializer=hivemind__pb2.PutSegmentRequest.SerializeToString,
                response_deserializer=hivemind__pb2.PutSegmentResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/hivemind.v1.HiveMind/GetFile',
                request_serializer=hivemind__pb2.GetFileRequest.SerializeToString,
                response_deserializer=hivemind__pb2.GetFileResponse.FromString,
                _registered_method=True)
        self.ReadPartial = channel.unary_unary(
                '/hivemind.v1.HiveMind/ReadPartial',
                request_serializer=hivemind__pb2.ReadPartialRequest.SerializeToString,
                response_deserializer=hivemind__pb2.ReadPartialResponse.FromString,
                _registered_method=True)
        self.GraphNeighbors = channel.unary_unary(
                '/hivemind.v1.HiveMind/GraphNeighbors',
                request_serializer=hivemind__pb2.GraphNeighborsRequest.SerializeToString,
                response_deserializer=hivemind__pb2.GraphNeighborsResponse.FromString,
                _registered_method=True)
        self.SearchCandidates = channel.unary_unary(
                '/hivemind.v1.HiveMind/SearchCandidates',
                request_serializer=hivemind__pb2.SearchCandidatesRequest.SerializeToString,
                response_deserializer=hivemind__pb2.SearchCandidatesResponse.FromString,
                _registered_method=True)
        self.ProposeSplit = channel.unary_unary(
                '/hivemind.v1.HiveMind/ProposeSplit',
                request_serializer=hivemind__pb2.ProposeSplitRequest.SerializeToString,
                response_deserializer=hivemind__pb2.ProposeSplitResponse.FromString,
                _registered_method=True)
        self.PutEdge = channel.unary_unary(
                '/hivemind.v1.HiveMind/PutEdge',
                request_serializer=hivemind__pb2.PutEdgeRequest.SerializeToString,
                response_deserializer=hivemind__pb2.PutEdgeResponse.FromString,
                _registered_method=True)
        self.PutEntity = channel.unary_unary(
                '/hivemind.v1.HiveMind/PutEntity',
                request_serializer=hivemind__pb2.PutEntityRequest.SerializeToString,
                response_deserializer=hivemind__pb2.PutEntityResponse.FromString,
                _registered_method=True)
        self.LookupEntity = channel.unary_unary(
                '/hivemind.v1.HiveMind/LookupEntity',
                request_serializer=hivemind__pb2.LookupEntityRequest.SerializeToString,
                response_deserializer=hivemind__pb2.LookupEntityResponse.FromString,
                _registered_method=True)


class HiveMindServicer:
    """HiveMind is the single shared gRPC service exposing every RPC this
    contract defines. A single service (rather than one per RPC-group) keeps
    the generated client/server surface simple -- engine/rpc/'s server
    implements HiveMindServer; engine/split/'s proposer_grpc.go (task-3.2.3)
    only calls HiveMindClient.ProposeSplit.
    """

    def PutSegment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPartial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeSplit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HiveMindServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.PutSegment,
                    request_deserializer=hivemind__pb2.PutSegmentRequest.FromString,
                    response_serializer=hivemind__pb2.PutSegmentResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=hivemind__pb2.GetFileRequest.FromString,
                    response_serializer=hivemind__pb2.GetFileResponse.SerializeToString,
            ),
            'ReadPartial': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPartial,
                    request_deserializer=hivemind__pb2.ReadPartialRequest.FromString,
                    response_serializer=hivemind__pb2.ReadPartialResponse.SerializeToString,
            ),
            'GraphNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphNeighbors,
                    request_deserializer=hivemind__pb2.GraphNeighborsRequest.FromString,
                    response_serializer=hivemind__pb2.GraphNeighborsResponse.SerializeToString,
            ),
            'SearchCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCandidates,
                    request_deserializer=hivemind__pb2.SearchCandidatesRequest.FromString,
                    response_serializer=hivemind__pb2.SearchCandidatesResponse.SerializeToString,
            ),
            'ProposeSplit': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeSplit,
                    request_deserializer=hivemind__pb2.ProposeSplitRequest.FromString,
                    response_serializer=hivemind__pb2.ProposeSplitResponse.SerializeToString,
            ),
            'PutEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.PutEdge,
                    request_deserializer=hivemind__pb2.PutEdgeRequest.FromString,
                    response_serializer=hivemind__pb2.PutEdgeResponse.SerializeToString,
            ),
            'PutEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.PutEntity,
                    request_deserializer=hivemind__pb2.PutEntityRequest.FromString,
                    response_serializer=hivemind__pb2.PutEntityResponse.SerializeToString,
            ),
            'LookupEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupEntity,
                    request_deserializer=hivemind__pb2.LookupEntityRequest.FromString,
                    response_serializer=hivemind__pb2.LookupEntityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivemind.v1.HiveMind', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivemind.v1.HiveMind', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HiveMind:
    """HiveMind is the single shared gRPC service exposing every RPC this
    contract defines. A single service (rather than one per RPC-group) keeps
    the generated client/server surface simple -- engine/rpc/'s server
    implements HiveMindServer; engine/split/'s proposer_grpc.go (task-3.2.3)
    only calls HiveMindClient.ProposeSplit.
    """

    @staticmethod
    def PutSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/PutSegment',
            hivemind__pb2.PutSegmentRequest.SerializeToString,
            hivemind__pb2.PutSegmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/GetFile',
            hivemind__pb2.GetFileRequest.SerializeToString,
            hivemind__pb2.GetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadPartial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/ReadPartial',
            hivemind__pb2.ReadPartialRequest.SerializeToString,
            hivemind__pb2.ReadPartialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/GraphNeighbors',
            hivemind__pb2.GraphNeighborsRequest.SerializeToString,
            hivemind__pb2.GraphNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/SearchCandidates',
            hivemind__pb2.SearchCandidatesRequest.SerializeToString,
            hivemind__pb2.SearchCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeSplit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/ProposeSplit',
            hivemind__pb2.ProposeSplitRequest.SerializeToString,
            hivemind__pb2.ProposeSplitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/PutEdge',
            hivemind__pb2.PutEdgeRequest.SerializeToString,
            hivemind__pb2.PutEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/PutEntity',
            hivemind__pb2.PutEntityRequest.SerializeToString,
            hivemind__pb2.PutEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.v1.HiveMind/LookupEntity',
            hivemind__pb2.LookupEntityRequest.SerializeToString,
            hivemind__pb2.LookupEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
